version: "3.8"

services:
  web:
    image: nomepierdo:latest
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    networks:
      - matdevnet
      - db_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=matdevnet"
        - "traefik.http.routers.nomepierdo.rule=Host(`nomepierdo.mmatdev.com`)"
        - "traefik.http.routers.nomepierdo.entrypoints=websecure"
        - "traefik.http.routers.nomepierdo.tls=true"
        - "traefik.http.routers.nomepierdo.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.nomepierdo.loadbalancer.server.port=3000"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - db_net
    volumes:
      - nomepierdo_pgdata:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  matdevnet:
    external: true
  db_net:
    driver: overlay
    attachable: true

volumes:
  nomepierdo_pgdata:
